# Generated by Django 4.2.7 on 2023-11-27 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="assigned_users",
        ),
        migrations.AddField(
            model_name="task",
            name="assigned_users",
            field=models.ManyToManyField(
                related_name="assigned_tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
