# Generated by Django 4.2.7 on 2023-11-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_remove_task_assigned_users_task_assigned_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(blank=True),
        ),
    ]
