# Generated by Django 4.2.7 on 2023-11-29 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0003_alter_task_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assigned_users",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
